### ISSUE TITLE
How to test the calibNAXP method plotting lines and planes

### ISSUE THREAD

**Issue by freelist** [baggepinnen/Robotlib.jl#20]
Hi, 
I see that the calibNAXP method has a parameter doplot that can be set to true in order to plot the lines and planes during the optimization. Is it actually working? I see that if we enable this parameter the package actually crashes, with errors on not defined variables "N_RB" in the main function or "p" in the plotPlanes function.

Is there a way to set up everything and actually plot the simulated lines and planes for hand-eye calibration of laser sensors?

I would really apprechiate to use this method.

Best regards,
D.

**Comment by baggepinnen** [comment]
Thanks for the issue! It appears that the plotting had not been updated in quite a while. I pushed a commit that makes it at least show something, but automatically choosing reasonable planes to plot is rather tricky so you might have to manually adjust the size of the planes etc. for it to look nice. 
The definition of the plot functions had to move to the file `Robotlib.jl` since the package does not depend on Plots.jl other than as a conditional dependency through `@requires`. You thus have to manually run `using Plots` before plotting works.

**Comment by baggepinnen** [comment]
@JuliaRegistrator register()

**Comment by baggepinnen** [comment]
@JuliaRegistrator register()
